import type { QuizConfig } from "@/types/quiz";

export const INDIA_QUIZ_CONFIG: QuizConfig = {
  country_code: "IN",
  total_questions: 12,
  questions: [
    {
      id: 1,
      key: "age",
      question: "How old are you?",
      type: "slider",
      slider: { min: 22, max: 55, step: 1, default: 28 },
      scoring_use: "Cohort formation",
    },
    {
      id: 2,
      key: "city",
      question: "Which city do you live in?",
      type: "dropdown",
      dropdown: {
        pinned: ["Bengaluru", "Mumbai", "Hyderabad", "Pune", "Delhi"],
        options: [
          { label: "Bengaluru", value: "Bengaluru" },
          { label: "Mumbai", value: "Mumbai" },
          { label: "Hyderabad", value: "Hyderabad" },
          { label: "Pune", value: "Pune" },
          { label: "Delhi", value: "Delhi" },
          { label: "Chennai", value: "Chennai" },
          { label: "Kolkata", value: "Kolkata" },
          { label: "Noida", value: "Noida" },
          { label: "Gurugram", value: "Gurugram" },
          { label: "Ahmedabad", value: "Ahmedabad" },
          { label: "Jaipur", value: "Jaipur" },
          { label: "Kochi", value: "Kochi" },
          { label: "Thiruvananthapuram", value: "Thiruvananthapuram" },
          { label: "Coimbatore", value: "Coimbatore" },
          { label: "Chandigarh", value: "Chandigarh" },
          { label: "Lucknow", value: "Lucknow" },
          { label: "Indore", value: "Indore" },
          { label: "Nagpur", value: "Nagpur" },
          { label: "Bhopal", value: "Bhopal" },
          { label: "Other", value: "Other" },
        ],
      },
      scoring_use: "Cohort + geography",
    },
    {
      id: 3,
      key: "salary_range",
      question: "Monthly in-hand salary?",
      type: "chips",
      options: [
        { label: "< \u20B930K", value: "<30K" },
        { label: "\u20B930-50K", value: "30-50K" },
        { label: "\u20B950-75K", value: "50-75K" },
        { label: "\u20B975K-1.2L", value: "75K-1.2L" },
        { label: "\u20B91.2-2L", value: "1.2-2L" },
        { label: "\u20B92L+", value: "2L+" },
      ],
      scoring_use: "Financial + Career bench",
    },
    {
      id: 4,
      key: "savings_rate",
      question: "Savings/investment rate?",
      type: "chips",
      options: [
        { label: "0%", value: "0%" },
        { label: "< 5%", value: "<5%" },
        { label: "5-10%", value: "5-10%" },
        { label: "10-20%", value: "10-20%" },
        { label: "20%+", value: "20%+" },
      ],
      scoring_use: "Savings percentile",
    },
    {
      id: 5,
      key: "term_insurance",
      question: "Do you have term life insurance?",
      type: "chips",
      options: [
        { label: "Yes", value: "yes" },
        { label: "No", value: "no" },
        { label: "Not Sure", value: "not_sure" },
      ],
      scoring_use: "Insurance risk flag",
    },
    {
      id: 6,
      key: "emi_burden",
      question: "EMIs as % of salary?",
      type: "chips",
      options: [
        { label: "No EMIs", value: "no_emi" },
        { label: "< 20%", value: "<20%" },
        { label: "20-40%", value: "20-40%" },
        { label: "40%+", value: "40%+" },
      ],
      scoring_use: "Debt burden",
    },
    {
      id: 7,
      key: "family_support",
      question: "Do you financially support your family?",
      type: "chips",
      options: [
        { label: "No", value: "no" },
        { label: "< 10%", value: "<10%" },
        { label: "10-20%", value: "10-20%" },
        { label: "20%+", value: "20%+" },
      ],
      tooltip: "Supporting family is strength. We adjust your benchmarks accordingly.",
      scoring_use: "Family-adjusted bench",
    },
    {
      id: 8,
      key: "industry",
      question: "Your industry?",
      type: "chips",
      options: [
        { label: "IT", value: "IT" },
        { label: "Finance", value: "Finance" },
        { label: "Consulting", value: "Consulting" },
        { label: "Healthcare", value: "Healthcare" },
        { label: "E-commerce", value: "E-commerce" },
        { label: "Manufacturing", value: "Manufacturing" },
        { label: "Government", value: "Government" },
        { label: "Other", value: "Other" },
      ],
      scoring_use: "Career cohort",
    },
    {
      id: 9,
      key: "experience_years",
      question: "Years of experience?",
      type: "slider",
      slider: { min: 0, max: 25, step: 1, default: 5, unit: "years" },
      scoring_use: "Career velocity",
    },
    {
      id: 10,
      key: "sleep_hours",
      question: "Hours of sleep per night?",
      type: "slider",
      slider: { min: 4, max: 10, step: 0.5, default: 7, unit: "hrs" },
      scoring_use: "Health score",
    },
    {
      id: 11,
      key: "exercise_days",
      question: "Exercise days per week?",
      type: "chips",
      options: [
        { label: "0 days", value: "0" },
        { label: "1-2 days", value: "1-2" },
        { label: "3-4 days", value: "3-4" },
        { label: "5+ days", value: "5+" },
      ],
      scoring_use: "Health score",
    },
    {
      id: 12,
      key: "emotional_state",
      question: "How are you feeling lately?",
      type: "chips",
      options: [
        { label: "Overwhelmed", value: "overwhelmed" },
        { label: "Managing", value: "managing" },
        { label: "Okay", value: "okay" },
        { label: "Thriving", value: "thriving" },
      ],
      scoring_use: "Emotional pulse \u2192 framing",
    },
  ],
};
